services:
  mongo:
    image: online-chat-mongo
    container_name: online-chat-mongo
    user: ${CONTAINERS_UID}:${CONTAINERS_GID}
    build:
      context: ./services/mongo
    ports:
      - 127.0.0.1:${MONGO_PORT}:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB}

  postgres:
    container_name: online-chat-postgres
    user: ${CONTAINERS_UID}:${CONTAINERS_GID}
    build:
      context: ./services/postgres
      args:
        - "pg_uid=${CONTAINERS_UID}"
        - "pg_gid=${CONTAINERS_GID}"
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

  nginx:
    image: online-chat-nginx
    container_name: online-chat-nginx
    build:
      context: ./services/nginx
      args:
        - "PORT=${NGINX_PORT}"
        - "FRONTEND_PORT=${FRONTEND_PORT}"
        - "BACKEND_PORT=${BACKEND_PORT}"
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./services/nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend

  frontend:
    image: online-chat-frontend
    container_name: online-chat-frontend
    user: ${CONTAINERS_UID}:${CONTAINERS_GID}
    build:
      context: ./services/frontend
      target: ${ENVIRONMENT}
    volumes:
      - ./services/frontend:/app
    ports:
      - 127.0.0.1:${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      APP_PORT: ${FRONTEND_PORT}
    depends_on:
      - backend


  backend:
    image: online-chat-backend
    container_name: online-chat-backend
    user: ${CONTAINERS_UID}:${CONTAINERS_GID}
    build:
      context: ./services/backend
      target: ${ENVIRONMENT}
    volumes:
      - ./services/backend:/app
    ports:
      - 127.0.0.1:${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mongo
      - postgres
    environment:
      LOG_MODE: ${BACKEND_LOG_MODE}
      NODE_ENV: ${ENVIRONMENT}
      APP_PORT: ${BACKEND_PORT}

      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      VERIFICATION_TOKEN_EXPIRES_IN: ${VERIFICATION_TOKEN_EXPIRES_IN}

      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      MAILER_LOGIN: ${MAILER_LOGIN}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      MAILER_SECURE: ${MAILER_SECURE}

      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB: ${MONGO_INITDB}